# Generated by Django 4.1 on 2023-03-10 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('registertime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usercoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_coupon', models.IntegerField(default=0)),
                ('reference', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairoilapi.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='Productpurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productprice', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('purchasetime', models.TimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairoilapi.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('landmark', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairoilapi.productpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hairoilapi.userregister')),
            ],
        ),
    ]
