# Generated by Django 4.1 on 2023-03-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoilapi', '0004_remove_usercoupon_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='issseller',
            field=models.BooleanField(default=False),
        ),
    ]
