# Generated by Django 4.1 on 2023-03-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoilapi', '0006_productpurchase_sellerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
