# Generated by Django 4.1 on 2023-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoilapi', '0007_userregister_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='buildingaddress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
