# Generated by Django 4.1 on 2023-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoilapi', '0010_order_prodid_order_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='reference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='purchasetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
