# Generated by Django 4.1 on 2023-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoilapi', '0011_userregister_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
