# Generated by Django 4.1 on 2023-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoilapi', '0012_alter_userregister_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='reference',
            field=models.CharField(default='', max_length=100),
        ),
    ]
