# Generated by Django 4.1 on 2023-03-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoilapi', '0002_userregister_unique_id_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='paymentcompletion',
            field=models.BooleanField(default=False),
        ),
    ]
